In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [4]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
element = arr_1d[2]
print(element)

row = arr_2d[1]
print(row)

especific_element = arr_2d[0,2]
print(especific_element)

subarray = arr_1d[1:4]
print(subarray)

3
[4 5 6]
3
[2 3 4]


In [11]:
reshaped_arr = arr_1d.reshape((5,1))
reshaped_arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
flattened_arr = arr_2d.flatten()
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [13]:
concatenated_arr = np.concatenate([arr_1d,arr_1d])
concatenated_arr

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [15]:
concatenated_arr_2d = np.concatenate([arr_2d, arr_2d], axis = 1)
concatenated_arr_2d

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [16]:
split_arr = np.split(arr_1d, 5)
split_arr

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [17]:
split_arr_2d = np.split(arr_2d,2, axis = 0)
split_arr_2d

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [18]:
transposed_arr = arr_2d.T
transposed_arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
addition = arr_1d + 2
print(addition)

multiplication = arr_2d *2
print(multiplication)

[3 4 5 6 7]
[[ 2  4  6]
 [ 8 10 12]]


In [20]:
sorted_arr = np.sort(arr_1d,)
sorted_arr

array([1, 2, 3, 4, 5])

In [21]:
sorted_arr_2d = np.sort(arr_2d, axis = 0)
sorted_arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
sorted_arr_2d_column = arr_2d[arr_2d[:,1].argsort()]
sorted_arr_2d_column

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
mask = arr_2d >3
mask

array([[False, False, False],
       [ True,  True,  True]])

In [24]:
filtered_arr = arr_2d[mask]
filtered_arr

array([4, 5, 6])

In [25]:
arr_2d[mask] = 0
arr_2d

array([[1, 2, 3],
       [0, 0, 0]])

In [26]:
hstacked_arr = np.hstack([arr_2d,arr_2d])
hstacked_arr

array([[1, 2, 3, 1, 2, 3],
       [0, 0, 0, 0, 0, 0]])

In [27]:
vstacked_arr = np.vstack([arr_2d,arr_2d])
vstacked_arr

array([[1, 2, 3],
       [0, 0, 0],
       [1, 2, 3],
       [0, 0, 0]])