Pandas Course

In [1]:
import pandas as pd

In [2]:
# Series 

my_series = pd.Series([10,20,30,40,50], index = ["a", "b", "c", "d", "e"])

type(my_series)

pandas.core.series.Series

In [4]:
print(my_series["a"])
print(my_series["b":"d"])

10
b    20
c    30
d    40
dtype: int64


In [5]:
print(my_series + 5)
print(my_series * 2)
print(my_series /2)

a    15
b    25
c    35
d    45
e    55
dtype: int64
a     20
b     40
c     60
d     80
e    100
dtype: int64
a     5.0
b    10.0
c    15.0
d    20.0
e    25.0
dtype: float64


In [10]:
print(my_series.dtype)
print(my_series.size)
print(my_series.shape)
print(my_series.head(3))
print(my_series.tail(3))
print(my_series.describe())
print(my_series.sort_values(ascending=False))

int64
5
(5,)
a    10
b    20
c    30
dtype: int64
c    30
d    40
e    50
dtype: int64
count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64
e    50
d    40
c    30
b    20
a    10
dtype: int64


In [11]:
data = { "Name": ["André", "Jimena", "Silvia", "Gala"],
        "Age":[21, 22, 30, 45],
        "City": ["Santa Ana", "Pozos", "Escazú", "Limon"]}

data

{'Name': ['André', 'Jimena', 'Silvia', 'Gala'],
 'Age': [21, 22, 30, 45],
 'City': ['Santa Ana', 'Pozos', 'Escazú', 'Limon']}

In [12]:
df = pd.DataFrame(data)
df

Name  Age       City
0   André   21  Santa Ana
1  Jimena   22      Pozos
2  Silvia   30     Escazú
3    Gala   45      Limon

In [13]:
data_list = [["André",21,"Santa Ana"],["Jimena",22,"Pozos"], ["Silvia",30,"Escazú"], ["Gala",45,"Limon"]]
data_list

[['André', 21, 'Santa Ana'],
 ['Jimena', 22, 'Pozos'],
 ['Silvia', 30, 'Escazú'],
 ['Gala', 45, 'Limon']]

In [14]:
df2 = pd.DataFrame(data_list, columns = ["Name", "Age", "City"])
df2

Name  Age       City
0   André   21  Santa Ana
1  Jimena   22      Pozos
2  Silvia   30     Escazú
3    Gala   45      Limon

In [15]:
import numpy as np

In [18]:
data_array = np.array( [[1,2,3],[4,5,6],[7,8,9]])
print(data_array)

df_array = pd.DataFrame(data_array, columns = ["a","b","c"])
df_array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [19]:
data = { "Name": ["André", "Jimena", "Silvia", "Gala"],
        "Age":[21, 22, 30, 45],
        "City": ["Santa Ana", "Pozos", "Escazú", "Limon"]}

df = pd.DataFrame(data)

df.to_csv("example.csv", index=False)

In [21]:
data = pd.read_csv("example.csv")
data

Name  Age       City
0   André   21  Santa Ana
1  Jimena   22      Pozos
2  Silvia   30     Escazú
3    Gala   45      Limon

In [22]:
df.to_excel("example.xlsx", index=False)

In [23]:
data_excel = pd.read_excel("example.xlsx")
data_excel

Name  Age       City
0   André   21  Santa Ana
1  Jimena   22      Pozos
2  Silvia   30     Escazú
3    Gala   45      Limon

In [26]:
data = { "Name": ["André", "Jimena", "Silvia", "Gala"],
        "Age":[21, 22, 30, 45],
        "City": ["Santa Ana", "Pozos", "Escazú", "Limon"]}

df = pd.DataFrame(data)
print(df.head(2))
print(df.tail(1))

     Name  Age       City
0   André   21  Santa Ana
1  Jimena   22      Pozos
   Name  Age   City
3  Gala   45  Limon


In [31]:
df[["Name", "City"]]

Name       City
0   André  Santa Ana
1  Jimena      Pozos
2  Silvia     Escazú
3    Gala      Limon

In [36]:
df[df["Age"] > 28]

Name  Age   City
1  Jimena   22  Pozos

In [37]:
df[df["Name"] == "Jimena"]

Name  Age   City
1  Jimena   22  Pozos

In [38]:
df[(df["City"] == "Limon") & (df["Age"] > 35)]

Name  Age   City
3  Gala   45  Limon

In [39]:
selected_cities = ["Limon", "Pozos"]

df[df["City"].isin(selected_cities)]

Name  Age   City
1  Jimena   22  Pozos
3    Gala   45  Limon

In [40]:
df[df["Name"].str.startswith("A")]

Name  Age       City
0  André   21  Santa Ana

In [41]:
df

Name  Age       City
0   André   21  Santa Ana
1  Jimena   22      Pozos
2  Silvia   30     Escazú
3    Gala   45      Limon

In [44]:
df.iloc[0:2]

Name  Age       City
0   André   21  Santa Ana
1  Jimena   22      Pozos

In [45]:
df.loc[df["Age"] > 25, ["Name","City"]]

Name    City
2  Silvia  Escazú
3    Gala   Limon

In [47]:
data = {
    "A":[1,2,np.nan,4,5],
    "B":[6,np.nan,8,9,10],
    "C":[11,12,13,np.nan,15]
}

df = pd.DataFrame(data)
df

A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   8.0  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [49]:
df.isnull().sum()

A    1
B    1
C    1
dtype: int64

In [50]:
df.dropna()

A     B     C
0  1.0   6.0  11.0
4  5.0  10.0  15.0

In [51]:
df

A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   8.0  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [52]:
df.dropna(inplace = True)
df

A     B     C
0  1.0   6.0  11.0
4  5.0  10.0  15.0